Factory/Models/Machine.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntries = new HashSet<EngineerMachine>();
    }
    public int MachineId { get; set; }
    public string MachineName { get; set; }
    public string InstallDate { get; set; }
    public ICollection<EngineerMachine> JoinEntries { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
      .Include(machine => machine.JoinEntries)
      .ThenInclude(join => join.Engineer)
      .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }
    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }
    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a Engineer to this Machine</h2>

<h2>Add a Engineer for: @Html.DisplayFor(model => model.MachineName)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select an Engineer")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to Machines", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a Machine</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.MachineName)
    @Html.TextBoxFor(model => model.MachineName)

    @Html.Label("Installation Date")
    @Html.TextBoxFor(model => model.InstallDate, new { @type = "date"})

    <input type="submit" value="Add New Machine" class="btn btn-default" />
}
<p>@Html.ActionLink("Show All Machines", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this Machine?</h2>

@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-default" />
}
<p>@Html.ActionLink("Back to Machines", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}
@using Factory.Models
@model Factory.Models.Machine;

<h2>Machine Overview</h2>
<hr />
<h3>Machine: @Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)</h3>
<h3>@Html.DisplayNameFor(model => model.InstallDate): @Html.DisplayFor(model => model.InstallDate)</h3>

@if(@Model.JoinEntries.Count == 0)
{
  <p>This Machine is currently not assigned to any Engineers.</p>
}
else
{
  <h4><u>Licensed Engineers for @Html.DisplayFor(model => model.MachineName)</u></h4>
    <ul>
    @foreach(var join in Model.JoinEntries)
    {
      <li>@join.Engineer.EngineerName</li>
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete"/>
      } 
    }
    </ul>
}
<p>@Html.ActionLink("Edit Machine Information", "Edit", new { id = Model.MachineId })
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.MachineName)
  @Html.EditorFor(model => model.MachineName)

  <input type="submit" value="Save" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to Machines", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}


@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machines</h1>
<hr />
@if (@Model.Count == 0)
{
<h3>There are no Machines Listed</h3>
}

@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
  @using (Html.BeginForm("Delete", "Machines", FormMethod.Get))
  {
    @Html.Hidden("id", @machine.MachineId)
    <input type="submit" value="Remove Machine" class="btn btn-default"/>
  }
}
<p>@Html.ActionLink("Add a new Machine", "Create", "Machines")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>