Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntries = new HashSet<EngineerMachine>();
    }
    public int EngineerId { get; set; }
    public string EngineerName { get; set; }
    public string HireDate { get; set; }
    public ICollection<EngineerMachine> JoinEntries { get; set; }

  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;
  
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine(){ MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntries)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine(){
          MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine License</h2>

<h2>Add a Machine License for: @Html.DisplayFor(model => model.EngineerName)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select a Machine")
    @Html.DropDownList("MachineId")

    <input type="submit" value="Save" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to Engineers", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Hire a new Engineer</h4>

@using (Html.BeginForm())
{

    @Html.LabelFor(model => model.EngineerName)
    @Html.TextBoxFor(model => model.EngineerName)

    @Html.Label("Select Machine")
    @Html.DropDownList("MachineId")

    @Html.Label("Hire Date")
    @Html.TextBoxFor(model => model.HireDate, new { @type = "date"})

    <input type="submit" value="Hire Engineer" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Engineers", "Index")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this Engineer?</h2>

@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-default"/>
}

@Html.ActionLink("Back To Engineer List", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)</h3>
<h3>@Html.DisplayNameFor(model => model.HireDate): @Html.DisplayFor(model => model.HireDate)</h3>
  @if(@Model.JoinEntries.Count == 0)
  {
  <p>This Engineer is not licensed for any Machines</p>
  }
  else
  {
    <h4>Machines @Html.DisplayFor(model => model.EngineerName) is licensed to work on:</h4>
    <ul>
    @foreach(var join in Model.JoinEntries)
    {
      <li>@join.Machine.MachineName</li>
      
      @using (Html.BeginForm("DeleteMachine", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete"/>
      } 
    }
    </ul>
  }

<p>@Html.ActionLink("Back to Engineer list", "Index")</p>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId})</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>

<h4>Edit: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.EngineerName)
  @Html.EditorFor(model => model.EngineerName)

  @Html.Label("Select a Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" class="btn btn-default" />
  
}

<p>@Html.ActionLink("Back to Engineers", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>Hired Engineers:</h1>

@if (@Model.Count == 0)
{
  <h3>No Engineers have been hired yet...</h3>
}

@foreach(Engineer engineer in Model)
{
  <li>@Html.ActionLink($"{engineer.EngineerName}", "Details", new { id = engineer.EngineerId })</li>
    @using (Html.BeginForm("Delete", "Engineers", FormMethod.Get))
  {
    @Html.Hidden("id", @engineer.EngineerId)
    <input type="submit" value="Remove Engineer" class="btn btn-default"/>
  }
}

<p>@Html.ActionLink("Add New Engineer", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>